 var firstName="swapnil"

 var Thise_is_very_log_name ="swapnil";
 var lastName="khante";

 //camelcase(standard function name)

 let userName="swapnil"

 let lastName="khante";

 let isLoggedIn= true;


 //pascalcase

 let UserName= "shubham";

 let LastName= "patil";


 / /3. snake_case
let user_name = "patil_shubham";
let total_price = 48.45;
let is_logged_in = true;

Screming_sanke_case

const MAX_SIZE=200;

